name: ML Project CI/CD Pipeline

# When the code push to github then it will run.

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Server Health Check
      run: |
      # Start the Flask API server in the backgroundpython app/webapp.py &
      # Wait for 5 seconds for the server to start sleep 5
      # Run the test script to check if the API is giving predictions or not curl http://127.0.0.1:5000/
      