name: ML Project CI/CD Pipeline

# When the code push to github then it will run.
on:
  push:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test Flask API Server
      run: |
        # Start the Flask API server in the background
        python app/webapp.py &
        # Wait for 5 seconds for the server to start
        sleep 5
        # Run the test script to check if the API is giving predictions or not
        python app/test_api.py
        